spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hospitaldb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: NEVER
      data-locations: classpath:data.sql

  security:
    user:
      name: ali
      password: 12345

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  servlet:
    context-path: /api/v1
